[package]
name = "auto-launch"
version = "0.1.0"
edition = "2021"
authors = ["zzzgydi <segydi@foxmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/zzzgydi/auto-launch.git"
keywords = ["launch", "auto launch", "startup", "login", "login-items"]

[target.'cfg(linux)'.dependencies]
dirs = "4.0"

[target.'cfg(macos)'.dependencies]
dirs = "4.0"

[target.'cfg(windows)'.dependencies]
winreg = { version = "0.10" }
